### PR TITLE
Update Swift-Extension.swift

### PR DESCRIPTION
**Pull request by nikoneufeld**
Added the power operator ** (as in FORTRAN) For Ints only to start with. Should use generic types

Please merge

### CODE REVIEW

**Comment by jakobneufeld** [comment]
No. You need to update your precedence group example: https://medium.com/@abhimuralidharan/how-to-create-a-custom-operator-like-operator-in-swift-55953c0c0bf2

>  Still a good job

**Comment by jakobneufeld** [comment]
Hallo papa

**Comment by jakobneufeld** [comment]
Ich werde jetzt es machen

**Comment by nikoneufeld** [comment]
Fixed in new commit

**Review by jakobneufeld — APPROVED** [review]
Very good

**Pull request merged**
